// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0tmzJlWPOvqKAY_wNlHqtRMVBtX7vTBc',
    appId: '1:49755067350:web:345dd2185fcdff32140a77',
    messagingSenderId: '49755067350',
    projectId: 'flux-chat-app',
    authDomain: 'flux-chat-app.firebaseapp.com',
    storageBucket: 'flux-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw6d7nlrsqyW40iIT3pOxdk1voVEBJIm0',
    appId: '1:49755067350:android:a8a5e18540de4110140a77',
    messagingSenderId: '49755067350',
    projectId: 'flux-chat-app',
    storageBucket: 'flux-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCju9J4TCTvj0TedTKrBld_mYZnsVrXmZU',
    appId: '1:49755067350:ios:9942b0172b34bda4140a77',
    messagingSenderId: '49755067350',
    projectId: 'flux-chat-app',
    storageBucket: 'flux-chat-app.appspot.com',
    iosClientId: '49755067350-br35k6sllnoefpc7hic97vf3b4r59ia2.apps.googleusercontent.com',
    iosBundleId: 'com.chat.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCju9J4TCTvj0TedTKrBld_mYZnsVrXmZU',
    appId: '1:49755067350:ios:9942b0172b34bda4140a77',
    messagingSenderId: '49755067350',
    projectId: 'flux-chat-app',
    storageBucket: 'flux-chat-app.appspot.com',
    iosClientId: '49755067350-br35k6sllnoefpc7hic97vf3b4r59ia2.apps.googleusercontent.com',
    iosBundleId: 'com.chat.chat',
  );
}
